seed: 42
img_size: 224
batch_size: 32
num_workers: 2

model_name: efficientnet_b0   # or resnet18 for speed
num_epochs: 8
lr: 0.0003
weight_decay: 0.0001

freeze_epochs: 2
device: auto  # auto/cuda/cpu

output_dir: outputs